name: Restart Minigame Bot

on:
  push:
    branches:
      - master
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restart 
        env: 
          API_KEY: ${{ secrets.API_KEY }}
          API_LINK: ${{ secrets.API_LINK }}
        run: |
          curl "$API_LINK" \
          -H 'Accept: application/json' \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer $API_KEY' \
          -X POST \
          -d '{"signal": "restart"}' 
        
